PRAGMA foreign_keys = ON;

CREATE TABLE `User` (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Account VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    SellerReputation DECIMAL(3, 2) DEFAULT 5.00,
    BuyerReputation DECIMAL(3, 2) DEFAULT 5.00
);

CREATE TABLE `Group` (
    GroupID INTEGER PRIMARY KEY AUTOINCREMENT,
    GroupName VARCHAR(100) NOT NULL,
    Company VARCHAR(100)
);

CREATE TABLE `Member` (
    MemberID INTEGER PRIMARY KEY AUTOINCREMENT,
    GroupID INTEGER NOT NULL,
    MemberName VARCHAR(100) NOT NULL,
    FOREIGN KEY (GroupID) REFERENCES `Group`(GroupID) ON DELETE CASCADE
);

CREATE TABLE `Product` (
    ProductID INTEGER PRIMARY KEY AUTOINCREMENT,
    SellerID INTEGER NOT NULL,
    Price DECIMAL(10, 2) NOT NULL CHECK (Price >= 0),
    ProductName VARCHAR(100) NOT NULL,
    Description TEXT,
    Condition VARCHAR(50) NOT NULL,
    TradeMethod VARCHAR(50) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Available',
    ImageUrl VARCHAR(255),
    FOREIGN KEY (SellerID) REFERENCES `User`(UserID)
);

CREATE TABLE `Product_Member_Rel` (
    RelID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductID INTEGER NOT NULL,
    MemberID INTEGER NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES `Product`(ProductID) ON DELETE CASCADE,
    FOREIGN KEY (MemberID) REFERENCES `Member`(MemberID) ON DELETE CASCADE
);

CREATE TABLE `Order` (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    BuyerID INTEGER NOT NULL,
    ProductID INTEGER NOT NULL UNIQUE,
    OrderPrice DECIMAL(10, 2) NOT NULL CHECK (OrderPrice >= 0),
    Status VARCHAR(20) DEFAULT 'Pending',
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BuyerID) REFERENCES `User`(UserID),
    FOREIGN KEY (ProductID) REFERENCES `Product`(ProductID)
);

CREATE TABLE `Wishlist` (
    WishID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    MemberID INTEGER NOT NULL,
    MaxPrice DECIMAL(10, 2) NOT NULL CHECK (MaxPrice >= 0),
    ConditionReq VARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES `User`(UserID) ON DELETE CASCADE,
    FOREIGN KEY (MemberID) REFERENCES `Member`(MemberID) ON DELETE CASCADE
);

CREATE TABLE `Review` (
    ReviewID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderID INTEGER NOT NULL UNIQUE,
    PackingScore INTEGER NOT NULL CHECK (PackingScore BETWEEN 1 AND 5),
    VideoScore INTEGER NOT NULL CHECK (VideoScore BETWEEN 1 AND 5),
    SpeedScore INTEGER NOT NULL CHECK (SpeedScore BETWEEN 1 AND 5),
    Comment TEXT,
    FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID) ON DELETE CASCADE
);

CREATE TABLE `ProductMessage` (
    MessageID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductID INTEGER NOT NULL,
    SenderID INTEGER NOT NULL,
    ReceiverID INTEGER NOT NULL,
    Content TEXT NOT NULL,
    MediaUrl VARCHAR(255),
    SentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ProductID) REFERENCES `Product`(ProductID) ON DELETE CASCADE,
    FOREIGN KEY (SenderID) REFERENCES `User`(UserID),
    FOREIGN KEY (ReceiverID) REFERENCES `User`(UserID)
);

CREATE TABLE `Chat` (
    ChatID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductID INTEGER NOT NULL,
    BuyerID INTEGER NOT NULL,
    SellerID INTEGER NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ProductID) REFERENCES `Product`(ProductID) ON DELETE CASCADE,
    FOREIGN KEY (BuyerID) REFERENCES `User`(UserID),
    FOREIGN KEY (SellerID) REFERENCES `User`(UserID)
);

CREATE TABLE `ChatMessage` (
    MessageID INTEGER PRIMARY KEY AUTOINCREMENT,
    ChatID INTEGER NOT NULL,
    SenderID INTEGER NOT NULL,
    Message TEXT NOT NULL,
    IsRead BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChatID) REFERENCES `Chat`(ChatID) ON DELETE CASCADE,
    FOREIGN KEY (SenderID) REFERENCES `User`(UserID)
);
